In [12]:
class xyz :
    def __init__(self , a , b,c) :
        self.a = a 
        self.b = b
        self.c = c 
    
    def test(self) :
        return ("this is my first test metond of xyz class ")
        
    def test1(self) :
        return ("this is a test1 meth of xyz class ")
    
    def test2(self) : 
        return ("this is my test2 meth of xyz class ")

In [13]:
p = xyz(1,2,3)

In [14]:
p.test()

'this is my first test metond of xyz class '

In [15]:
class xyz1(xyz) :          # this is inheriting xyz class
    pass

In [17]:
q = xyz1()           # we need use like xyz class

TypeError: __init__() missing 3 required positional arguments: 'a', 'b', and 'c'

In [19]:
q = xyz1(3,4,5)         # we have used a,b, c

In [15]:
q.test1()

this is a test1 meth of xyz class 


In [22]:
class xyz1(xyz) :
    def test(self) :
        print("this is a test meth aviable in xyz1")
        
        
    

In [23]:
g = xyz1(4,5,6)

In [24]:
g.test()               # if parent is haveing same functiona and child is also haveing function name then,
                       # we will get function from child class only, child has its own way of working

this is a test meth aviable in xyz1


In [26]:
class xyz:
    def __init__(self, a,b,c) :
        self.a= a 
        self.b= b 
        self.c= c 
        
        
    def test(self) : 
        print("this is a meth of xyz class ")
    
class xyz1:
    
    def __init__(self , p,q,v) :
        self.p = p 
        self.v = v 
        self.q = q 
        
    def test1(self) : 
        print("this is a meth form class xyz1")
        
class child(xyz1,xyz):
    def __init__(self , *args):                    # multiclass inhereitance
        xyz.__init__(self,*args) 
        xyz1.__init__(self,*args)

In [31]:
n = child(4,5,6)             # in this case child is considering first value same for both xyz and xyz1  using args and __init__

In [28]:
n.p              

4

In [29]:
n.a

4

In [25]:
class xyz:
    def __init__(self, a,b,c) :
        self.a= a 
        self.b= b 
        self.c= c 
        
        
    def test(self) : 
        print("this is a meth of xyz class ")
    
class xyz1:
    
    def __init__(self , p,q,v) :
        self.p = p 
        self.v = v 
        self.q = q 
        
    def test1(self) : 
        print("this is a meth form class xyz1")
        
class child(xyz1,xyz):
    def __init__(self , *args ,**kwargs):                    # multiclass inhereitance
        xyz.__init__(self,*args) 
        xyz1.__init__(self,**kwargs)
    

In [52]:
n = child(4,5,6,p = 3,q = 4,v  = 5)         # here we are using **kwargs and 

In [53]:
n.p      

3

In [54]:
n.q

4

In [55]:
n.a

4

In [56]:
n.test1()

this is a meth form class xyz1


In [57]:
n.test()

this is a meth of xyz class 


In [32]:
class xyz:
    def __init__(self, a,b,c) :
        self.a= a 
        self.b= b 
        self.c= c 
        
                                       # multilevel inheritance
    def test(self) : 
        print("this is a meth of xyz class ")
    
class xyz1(xyz):
        
    def test1(self) : 
        print("this is a meth form class xyz1")
        
class xyz2(xyz1) :
    def test2(self) :
        print("this is a meth form class 2")

class xyz3(xyz2):
    def test3(self) : 
        print("this is my meth form class xyz3")
        

In [33]:
v = xyz2(5,6,7)

In [34]:
m = xyz3(4,5,6)

In [ ]:
q1 - create a file class for reading data from respective file with a method name read and write   . 
q2  - try to inherit read and write method form parent class to child class to perform read and write operation 

In [ ]:
import logging 

logging.basicConfig(filename="list.log",level=logging.DEBUG,format="%(asctime)s %(levelname)s %(message)s",filemode='w')


class File:
    def __init__(self,filename):
        logging.info("Creating file instance varibale")
        self.file = filename

    def read(self):
        logging.info("executing read method")
        try:
            with open(f"{self.file}.txt",'r') as f:
                data = f.read()
                return data
        except FileNotFoundError as e:
            logging.error("Error occured while opening the file ")
            logging.exception(f"Error is {e}")

    def write(self,data):
        logging.info("executing write method")
        try:
            with open(f"{self.file}.txt",'w') as f:
                data = f.write(data)
        except FileNotFoundError as e:
            logging.error("Something is going wrong")
            
obj = File("abc")


In [70]:
class readFile:
    def __init__(self,fileObj, lines):
        self.file = fileObj
        self.lines = lines
    def readFile(self):
        file2=open(self.file,'r')
        line=file2.readline()
        while(line!=""):
            print(line)
            line=file2.readline()

    def writeFile(self):
        content_write = open(self.file,'w')
        content_write.writelines(lines)
        content_write.close()
        
class readFile1(readFile):
    def readFile1(self):
        print("inheritance of readFile class")

file1 = r'test1.txt'
lines = 'Inserted Lines .......'

read_write = readFile1(file1,lines)
read_write.writeFile()
read_write.readFile()


Inserted Lines .......


In [ ]:
class fileopeartion:
    def __init__(self,filepath):
        self.filepath = filepath
    def read(self):
        try:
            f = open(self.filepath,"r+")
            print(f.read())
        except Exception as e:
            print(e)
        f.close()
    def write(self,writings=""):
        try:
            f = open(self.filepath,"a")
        except Exception as e:
            print(e)
        f.write(writings)
        f.close()
class child(fileopeartion):
    pass


In [ ]:
class file_read(object):
    def __init__(self,filename) -> None:
        self.file = filename
        
class read(file_read):
    def read(self):
        try : 
            open_file = open(self.file, "r")
            self.read_file = open_file.read()
            open_file.close()
            return self.read_file
        except Exception as e :
            return e 
    
class write(file_read) :
    def write(self,*args):
        try : 
            open_file = open(self.file, "w")
            for ele in args:
                open_file.write(ele)
            return True
        except Exception as e :
            return e


In [ ]:
class filetask:
    def __init__(self, filename,filetype):
        self.filename=filename
        self.filetype=filetype
        
    def file_write(self):
        f=open(self.filename,'w')
        f.write('this is myc class task')
        f.close()
        
    def file_read(self):
        f=open(self.filename,'r')
        print(f.read())
        f.close()
            
class child(filetask):
    pass
     
test1=filetask('testingclass','.txt') 
test2=child('testingchild','.txt')


# ENCAPSULATION
## Public private and protected

In [74]:
class test : 
    def __init__(self , a,b,c) :
        self.a = a 
        self.b = b 
        self.c = c 
        
class test1(test) :
    pass
u = test(4,5,6)

In [75]:
v = test1(3,4,5)

In [3]:
class test : 
    def __init__(self ) :
        self.__a = 4                 # _a is protected variable( single "_")

        
class test1(test) :
    def __init__(self): 
        self.__a = 7


u = test()

In [108]:
u.__a

AttributeError: 'test' object has no attribute '__a'

In [109]:
v = test1()

In [110]:
v.__a

AttributeError: 'test1' object has no attribute '__a'

In [39]:
class test:
    def __init__(self,a,b,c,h):
        self._a = a    # protected
        self.__b= b    # private
        self.c = c     # public
        self.h = h
    
class test1(test) :
    pass
    
v = test(4,5,6,8)

In [42]:
v.c               # public       other than h or c we can acces values, unless we see the code

6

In [38]:
v._test__b       # private        # private variable can only be accessed using _classname__

5

In [36]:
u._test__b        # private             # child can also access using _classname__

4

In [21]:
v._a             # protected

4

In [22]:
v.c

6

In [23]:
u = test1(3,4,7)

In [24]:
u.c

7

In [25]:
u._a

3

In [26]:
u._test1__b

AttributeError: 'test1' object has no attribute '_test1__b'

In [99]:
class bonousclaculator:
    def __init__(self, empid , emprating) :
        self.empid = empid
        self.emprating = emprating
        self._empmail = "fdsfsfssf@gmail.com"
        self.__bonusforratingA = "70%"
        self.__bonusforraringB = "60%"
        self.__bonusforratinC = "40%"
    
    def bonuscalculator(self) :
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus
        elif self.emprating == "B" :
            bonus = self.__bonusforraringB
            return bonus
        else :
            bonus = self.__bonusforratinC
            return bonus

In [100]:
emp1 = bonousclaculator(101 , "A")
emp2 = bonousclaculator(102 , "B")
emp3 = bonousclaculator(103, "C")

In [101]:
emp1.bonuscalculator()

'70%'

In [102]:
emp2.bonuscalculator()

'60%'

In [103]:
emp3.bonuscalculator()

'40%'

In [104]:
emp1.empid = 104

In [105]:
emp1.empid

104

In [106]:
emp1.emprating= "B"

In [107]:
emp1.bonuscalculator()

'60%'

In [108]:
emp1.__bonusforraringB = "90%"       #  private varibale cant be changed

In [109]:
emp1.bonuscalculator()

'60%'

In [110]:
emp2.bonuscalculator()

'60%'

In [111]:
emp2.bonuscalculator()

'60%'

In [112]:
emp2.empid = 34543543

In [113]:
emp2.empid

34543543

In [114]:
emp2.__bonusforraringB = "fsadfsafs"

In [115]:
emp2._bonousclaculator__bonusforraringB

'60%'

In [118]:
emp2._bonousclaculator__bonusforraringB  = "435456"       # private variable can also be changed if we use single _ and
                                                          # classname and variable name with __ 

In [166]:
emp2._bonousclaculator__bonusforraringB 

'435456'

In [185]:
emp1._empmail 

'fdsfsfssf@gmail.com'

In [119]:
emp1._empmail  = "sudhanshu@gmail.com"       # protected can be changed like this

In [120]:
emp1._empmail

'sudhanshu@gmail.com'

In [189]:
class xyz():
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
    def test (self):
        print ("machine")

class xyz1(xyz):
    def __init__(self,p,q,r):
        self.p=p
        self.q=q
        self.r=r
    def test1(self):
        print ("learning")
class xyz2(xyz1):
    def test2(self):
        print ("ineuron")


In [190]:
v  = xyz2(3,4,5)

In [ ]:
v.test

In [195]:
def checkPrime():
    ''' Checks if a number is Prime. Keeps on asking
        for an input in correct form, >1 & an integer
        '''
    while True:
        try:
            num=int(input('Enter an integer'))
            if num>1:
                for i in range(2, num):
                    
                    if (num % i)==0:
                        pss
                        #print(num, ' is a not prime number')
                        #break
                
                    else:
                        print(num, ' is a prime number')
                        break
                        
                break       
                        
                
            else:
                print('Please enter a number >1')
        except:
            print('Please enter a valid input, an integer')
checkPrime()


Enter an integer4564
Please enter a valid input, an integer
Enter an integer456
Please enter a valid input, an integer
Enter an integer435
435  is a prime number


In [196]:
def largest_arr(*args):
    lagest_list_iter=0
    lagest_list=0
    l=[]
    for i in args:
        if type(i)==list or type(i)==tuple or type(i)==set:
            for j in i:
                l.append(j)
                lagest_list_iter=max(l)
            return lagest_list_iter    
                
        else:
            for i in args:
                l.append(i)
                lagest_list=max(l)
            return lagest_list


In [197]:
a = 50
iter(a)

TypeError: 'int' object is not iterable

In [198]:
b = [4,5,6]

In [200]:
type(iter(b))

list_iterator

In [204]:
if list in [list, tuple, set]:
    print("do someting ")

do someting 


In [208]:
import array as arr

In [223]:
a = arr.array('f' , [1,2,3,4])
a

array('f', [1.0, 2.0, 3.0, 4.0])

In [213]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [214]:
np.asanyarray([3,5,67,67])

array([ 3,  5, 67, 67])

In [215]:
np.asanyarray([34,6565,76,7,6])

array([  34, 6565,   76,    7,    6])

In [219]:
for i in a:
    print(i)

1.0
2.0
3.0
4.0


In [224]:
class parent:
    def __init__(self, p, q, r):
        self.p = p
        self._q = q
        self.__r = r
        
class child(parent):
    pass

c1 = child(4,5,6)

# How is  this possible??? 
c1.z = 435
c1.z

435

In [225]:
a = 10 

In [226]:
c2 = child(4,5,6)

In [227]:
c2.z

AttributeError: 'child' object has no attribute 'z'

In [233]:
class bonuscalculator:
    def __init__(self,empid, emprating):
        self.empid = empid
        self.emprating = emprating
        self.__bonusforratingA = "70%"
        self.__bonusforratingB = "60%"
        self.__bonusforratingC = "40%"

    def bonuscalc(self):
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus
        elif self.emprating == "B":
            bonus = self.__bonusforratingB
            return bonus
        else : 
            bonus = self.__bonusforratingC
            return bonus ,self.empid

emp1 = bonuscalculator(101, "A")
emp2 = bonuscalculator(102, "B")
emp3 = bonuscalculator(103, "C")
emp1.bonuscalc()
emp2.bonuscalc()



'60%'

In [234]:
emp3.bonuscalc()

('40%', 103)

In [236]:
class bonuscalculator:
    def __init__(self,empid,emprating):
        self.empid = empid
        self.emprating = emprating
        self._empmail = "abcd@gmail.com"
        self.__bonusforratingA = "70%"
        self.__bonusforratingB = "60%"
        self.__bonusforratingC = "40%"
        
    def bonuscalculator(self):
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus ,self.empid
        elif self.emprating == "B":
            bonus = self.__bonusforratingB
            return bonus,self.empid
        else:
            bonus = self.__bonusforratingC
            return bonus,self.empid
emp1 = bonuscalculator(101,"A")
emp2 = bonuscalculator(102,"B")
emp3 = bonuscalculator(103,"C")
emp1.bonuscalculator()
emp2.bonuscalculator()



('60%', 102)

In [243]:
class Xyz:
    objCount = 0
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
        Xyz.objCount += 1
        
    def test(self):
        print("Inside test method")
        
    def test1(self):
        print("Inside the test1 method")
        
    def test2(self):
        print("Inside the test2 method")

p = Xyz(1,2,3)
p1 = Xyz(2,3,4)
p1.objCount

2

In [244]:
p2 = Xyz(2,3,4)

In [242]:
p1.objCount


3